// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARkAGXMET0UlGc4SLayUOXSRjfLBvh3B8',
    appId: '1:785862564230:web:ade5e1c072fdfb11097407',
    messagingSenderId: '785862564230',
    projectId: 'buzz-49bf5',
    authDomain: 'buzz-49bf5.firebaseapp.com',
    storageBucket: 'buzz-49bf5.appspot.com',
    measurementId: 'G-01TW8HSVFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQw5V6AUhfGDEYR4U2W94u2t6T2kyYBdw',
    appId: '1:785862564230:android:a12b140c838c5792097407',
    messagingSenderId: '785862564230',
    projectId: 'buzz-49bf5',
    storageBucket: 'buzz-49bf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXwBH-YaZLMe6pcDpYQeZ7oJuDEY6KM3c',
    appId: '1:785862564230:ios:2168bf693cec7af0097407',
    messagingSenderId: '785862564230',
    projectId: 'buzz-49bf5',
    storageBucket: 'buzz-49bf5.appspot.com',
    iosBundleId: 'com.example.buzz',
  );
}
